language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36

install: pip install tox

stages:
  - name: tests
    if: type IN (push, pull_request)

jobs:
  include:
    - stage: tests
      name: "Code Style Check"
      python: 3.6
      before_script:
        - pip install tox-travis
      script: tox -e flake8

notifications:
  email: false
