version: '3.2'

# Environment variables here will override values in /config/config.ini

networks:
  net_registry:
    driver: bridge
  net_aggregator:
    driver: bridge

services:

  # REGISTRY DB AND APP

  db_registry:
    hostname: db_registry
    image: postgres:9.6
    environment:
      POSTGRES_USER: reg_user
      POSTGRES_DB: reg_db
      POSTGRES_PASSWORD: reg_pass
    ports:
      - 5432
    volumes:
      - ./db/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - net_registry

  app_registry:
    hostname: app_registry
    image: cscfi/beacon-network
    depends_on:
      - db_registry
    environment:
      APP_HOST: "0.0.0.0"
      DB_HOST: db_registry
      DB_PORT: 5432
      CONFIG_FILE: /app/config/config.ini
      BEACON_RUN_APP: registry
      DEBUG: "true"
    links:
      - db_registry
    ports:
      - 3000:3000
    networks:
      - net_registry

  # AGGREGATOR DB AND APP

  db_aggregator:
    hostname: db_aggregator
    image: postgres:9.6
    environment:
      POSTGRES_USER: agg_user
      POSTGRES_DB: agg_db
      POSTGRES_PASSWORD: agg_pass
    ports:
      - 5432
    volumes:
      - ./db/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - net_aggregator

  app_aggregator:
    hostname: app_aggregator
    image: cscfi/beacon-network
    depends_on:
      - db_aggregator
    environment:
      APP_HOST: "0.0.0.0"
      DB_HOST: db_aggregator
      DB_PORT: 5432
      CONFIG_FILE: /app/config/config.ini
      BEACON_RUN_APP: aggregator
      DEBUG: "true"
    links:
      - db_aggregator
    ports:
      - 3001:3001
    networks:
      - net_aggregator
